name: Test IF Block
on: 
   workflow_dispatch:
     inputs:
      rgName:
        type: choice
        description: Chose the resource group
        options:
        - sachin-demo
        - sachin-sandbox
        - sachin-test
        - sachin-qa

env: 
    envName: ${{ github.event.inputs.rgName }}|awk -F'-' '{print $2}'

       
jobs: 
    check_if_block:
      steps:
        - name: Check If Block
          
        - if: ${{ env.envName == 'test' }}
          run: |
            echo "This is Test related env"
            echo "Env name is ${envName} and secret is ${SQLSecret}"
          env:
            SQLSecret: Test
            
        - if: ${{ env.envName == 'qa' }}
          run: |
            echo "This is QA related env"
            echo "Env name is ${envName} and secret is ${SQLSecret}"
          env:
            SQLSecret: QA
            
