name: Test IF Block
on: 
    workflow_dispatch:
      inputs:
       rgName:
        type: choice
        description: Chose the resource group
        options:
        - sachin-demo
        - sachin-sandbox
        - sachin-test
        - sachin-qa

env: 
    envName: ${{ github.event.inputs.rgName }}

       
jobs: 
    check_if_block:
      runs-on: ubuntu-latest
      steps:   
        - name: Testing_IF_BLOCK
        - if: ${{ env.envName == 'sachin-test' }}
          run: |
            echo "This is Test related env"
            echo "Env name is ${envName} and secret is ${SQLSecret}"
          env:
            SQLSecret: Test
            
        - if: ${{ env.envName == 'sachin-qa' }}
          run: |
            echo "This is QA related env"
            echo "Env name is ${envName} and secret is ${SQLSecret}"
          env:
            SQLSecret: QA
            
